<div class="row">
  <div class="col col-md-4">
    
    <form action="../komunitas/store" method="POST">
      <div class="form-group">
        <label>Name</label>
        <input type="text" class="form-control" name="name" placeholder="Enter name">
      </div>
      <div class="form-group">
        <label>Contact</label>
        <input type="text" class="form-control" name="contact" placeholder="contact">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>