<div class="row">
  <div class="col col-md-4">
    <form action="../../komunitas/update" method="POST">
      <div class="form-group">
          <input type="hidden" class="form-control" name="id" placeholder="Enter name" value="<?php echo $data->id;  ?>">
        <label>Name</label>
        <input type="text" class="form-control" name="name" placeholder="Enter name" value="<?php echo $data->name;  ?>">
      </div>
      <div class="form-group">
        <label>Contact</label>
        <input type="text" class="form-control" name="contact" placeholder="contact" value="<?php echo $data->contact;  ?>">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>